# Generated by Django 3.1.7 on 2021-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
